### PR TITLE
Replace stop and remove command with docker down.

### PR DESCRIPTION
**Pull request by appleboy**
Hi

I test my app using this repo and the following are my test scripts.

``` sh
docker-compose -p ${RANDOM} -f docker/docker-compose.testing.yml run app
docker-compose -p ${RANDOM} -f docker/docker-compose.testing.yml down
```

I suggest `down` command better than `stop` and `rm` command. You don't need execute couple command.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, good suggestion, but would you like to introduce yourself.. maybe say a couple of words about the proposed change? Thanks :+1:

**Comment by appleboy** [comment]
@alexellis I updated my PR description.

**Comment by appleboy** [comment]
ping @alexellis

**Comment by alexellis** [comment]
Merged. Thanks.

**Pull request closed without merging**
