### PR TITLE
Adafruit

### PR DESCRIPTION
**Pull request by alexellis**
Support adafruit through cheerio HTML parser and product ID list.

### CODE REVIEW

**Comment by alexellis** [comment]
@lurch did you fancy doing a review of merging in Adafruit support?

**Comment by lurch** [comment]
Afraid I can't "test" it until it's been pushed live to http://stockalert.alexellis.io/ (I have no interest in installing docker).
Looking at the "Files changed" tab on this PR, I'd say it seems a bit inconsistent that some of the "fetchers" are initialised just as `new Pihut(modules)` (i.e. all the 'data' is embedded within pihut.js) but other "fetchers" are initialised as `new Adafruit(modules, ["2816", "2817", "2885"], "https://www.adafruit.com/categories/813")` (i.e. all the 'data' is embedded within index.js).

Other than that I don't have any feedback as I'm not a Node.js programmer.

**Comment by alexellis** [comment]
@lurch Thanks. 

The constructor thing is a good point. Now that Pihut and Pimoroni have converged closer in a recent commit. They are both using json files now. I may use the same class and pass a list of URLs through the constructor along with the modules map. They are all probably going to be more verbose.

It's live on the site now if you want to check it out. Adafruit currently have no stock though. The HTML is not great for inferring from a single element whether a product is a PI Zero or whether it has stock so I added cheerio (like a server-side dom query).

Docker could be installed in a VM if you did ever want to play with it on your own machine.

**Comment by lurch** [comment]
Now that Adafruit have some stock of PiZeros (thanks for pointing it out!), I had another look at their website :-)
While they currently don't show stock-levels for the PiZero, there _are_ some other products on that [page](https://www.adafruit.com/categories/813) that **do** list their stock levels (e.g. the Explorer Phat is listed as "63 IN STOCK"). So maybe you could update your Adafruit-scraper to parse these (optional) stock numbers too, just in case the Pi Zero items get updated with stock numbers at some point? ;-)
(Or maybe the Zeros always sell out so quickly, that Adafruit will never show stock numbers for them)

**Comment by alexellis** [comment]
@lurch I see where you are going with the stock numbers. I'll have to have another look once there is something available again. Jon at Pimoroni told me that they actually have a proper shop API - I don't know whether it's easy to get access to, but that would be doing things 'properly' and may be less portable.

**Pull request merged**
