### PR TITLE
Add new Pimoroni 'cctv' Zero kit

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks @lurch - lgtm. Did you want to update the unit test under `test/pimoroniTest.js` too? 

I put an update out for package.json so you may want to rebase from master.

```
$ npm install
$ npm test
```

**Comment by lurch** [comment]
This was only an edit-on-github change (after I spotted https://shop.pimoroni.com/products/pi-zero-cctv-kit-little-bro ), I haven't checked out the code or tried running it. I'll leave the unit tests up to you :)

**Comment by lurch** [comment]
Ah, looks like Pimoroni have changed the page-URL since earlier, so perhaps you need to use https://shop.pimoroni.com/products/pi-zero-cctv-kit-little-bro.js instead?

Ping @Gadgetoid again ;-)

**Comment by lurch** [comment]
Nope, forget that, it seems to have changed back to https://shop.pimoroni.com/products/pi-zero-cctv-kit-smol-bro again! (?)

**Comment by alexellis** [comment]
Updated again, btw Adafruit have stock now too :)

**Pull request merged**
